<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('products')->delete();

        \DB::table('products')->insert(array(
            0 =>
            array(
                'id' => 11,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/soap.jpeg',
                'product_name' => '肥皂',
                'description' => '化工肥皂，味道最經典!',
                'price' => '27',
                'ori_price' => '50',
                'category' => '肥皂',
                'selected' => NULL,
            ),
            1 =>
            array(
                'id' => 12,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/sofa.png',
                'product_name' => '大沙發',
                'description' => '醉在大沙發',
                'price' => '25000',
                'ori_price' => '40000',
                'category' => '沙發',
                'selected' => NULL,
            ),
            2 =>
            array(
                'id' => 13,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/travelBox.png',
                'product_name' => '行李箱',
                'description' => '骨董行李箱招標',
                'price' => '3500',
                'ori_price' => '3700',
                'category' => '行李箱',
                'selected' => NULL,
            ),
            3 =>
            array(
                'id' => 14,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/rug.png',
                'product_name' => '地毯',
                'description' => '每人每戶家中都該有地毯吧',
                'price' => '12000',
                'ori_price' => '22000',
                'category' => '地毯',
                'selected' => NULL,
            ),
            4 =>
            array(
                'id' => 15,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/TV.png',
                'product_name' => '電視',
                'description' => '過年就要換新電視',
                'price' => '13000',
                'ori_price' => '25000',
                'category' => '電視',
                'selected' => NULL,
            ),
            5 =>
            array(
                'id' => 16,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/clamp.jpg',
                'product_name' => '晾衣夾',
                'description' => '晾衣服總不能只用掛的吧',
                'price' => '5',
                'ori_price' => '8',
                'category' => '夾子',
                'selected' => NULL,
            ),
            6 =>
            array(
                'id' => 18,
                'pic_name' => 'NB',
                'pic_dir' => './pictureTarget/pc.png',
                'product_name' => '筆電',
                'description' => '筆記型電腦，四海皆為辦公室。',
                'price' => '29999',
                'ori_price' => '35000',
                'category' => '筆電',
                'selected' => NULL,
            ),
            7 =>
            array(
                'id' => 19,
                'pic_name' => '吸塵器',
                'pic_dir' => './pictureTarget/vaccum2.jpg',
                'product_name' => '高級吸塵器',
                'description' => '解決家庭紛爭神器',
                'price' => '18999',
                'ori_price' => '30000',
                'category' => '吸塵器',
                'selected' => NULL,
            ),
            8 =>
            array(
                'id' => 20,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/vaccum.jpg',
                'product_name' => '吸塵器',
                'description' => '偶爾故障時夫妻需先打一架看誰掃地。',
                'price' => '8999',
                'ori_price' => '15000',
                'category' => '吸塵器',
                'selected' => NULL,
            ),
            9 =>
            array(
                'id' => 21,
                'pic_name' => '冰箱',
                'pic_dir' => './pictureTarget/refrigerator-2420419_1280.png',
                'product_name' => '大冰箱',
                'description' => '只要家裡有冰箱，食物都能放香香',
                'price' => '27900',
                'ori_price' => '58099',
                'category' => '冰箱',
                'selected' => NULL,
            ),
            10 =>
            array(
                'id' => 22,
                'pic_name' => '洗衣機',
                'pic_dir' => './pictureTarget/washing-machine.jpg',
                'product_name' => '洗衣機',
                'description' => '雖然有了一台洗衣機，但免不了擲杯誰要去晾衣服',
                'price' => '30000',
                'ori_price' => '19999',
                'category' => '洗衣機',
                'selected' => NULL,
            ),
            11 =>
            array(
                'id' => 23,
                'pic_name' => '燈泡',
                'pic_dir' => './pictureTarget/lightbulb-2010022_1280.jpg',
                'product_name' => '燈泡',
                'description' => '點一顆光明燈，不怕半夜老爺子駕崩',
                'price' => '39',
                'ori_price' => '50',
                'category' => '燈泡',
                'selected' => NULL,
            ),
            12 =>
            array(
                'id' => 24,
                'pic_name' => '墨鏡',
                'pic_dir' => './pictureTarget/sunglasses.jpg',
                'product_name' => '墨鏡',
                'description' => '與偉大的金正恩同志同款(敬禮 //',
                'price' => '200',
                'ori_price' => '500',
                'category' => '墨鏡',
                'selected' => NULL,
            ),
            13 =>
            array(
                'id' => 25,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/wifi.png',
                'product_name' => 'wifi 機',
                'description' => '多了wifi 常常和wife say Hi',
                'price' => '2900',
                'ori_price' => '3500',
                'category' => 'wifi',
                'selected' => NULL,
            ),
            14 =>
            array(
                'id' => 26,
                'pic_name' => '冰箱',
                'pic_dir' => './pictureTarget/refrige.jpg',
                'product_name' => '冰箱',
                'description' => '節能冰箱，為您的家庭生活省下更多成本，更多關愛。',
                'price' => '20000',
                'ori_price' => '30000',
                'category' => '冰箱',
                'selected' => NULL,
            ),
            15 =>
            array(
                'id' => 27,
                'pic_name' => '冰箱',
                'pic_dir' => './pictureTarget/refrige2.png',
                'product_name' => '冰箱2',
                'description' => '保鮮無憂，冰箱守護您的食材鮮美，每一天。',
                'price' => '21000',
                'ori_price' => '31000',
                'category' => '冰箱',
                'selected' => NULL,
            ),
            16 =>
            array(
                'id' => 28,
                'pic_name' => '冰箱',
                'pic_dir' => './pictureTarget/refrige3.jpg',
                'product_name' => '多門大冰箱',
                'description' => '時尚設計，冰箱不僅是家電，更是您生活的時尚指標。',
                'price' => '45000',
                'ori_price' => '49000',
                'category' => '冰箱',
                'selected' => NULL,
            ),
            17 =>
            array(
                'id' => 29,
                'pic_name' => '冰箱',
                'pic_dir' => './pictureTarget/refrige4.jpg',
                'product_name' => '紅色大冰箱',
                'description' => '智慧冷藏，為您帶來更便利、更智慧的生活體驗。',
                'price' => '35000',
                'ori_price' => '39000',
                'category' => '冰箱',
                'selected' => NULL,
            ),
            18 =>
            array(
                'id' => 30,
                'pic_name' => '冰箱',
                'pic_dir' => './pictureTarget/refrige5.jpg',
                'product_name' => '小冰箱',
                'description' => '全新冰箱，讓您的廚房更有品味，更具現代風格。',
                'price' => '5000',
                'ori_price' => '8000',
                'category' => '冰箱',
                'selected' => NULL,
            ),
            19 =>
            array(
                'id' => 31,
                'pic_name' => '冰箱',
                'pic_dir' => './pictureTarget/refrigerator-2420419_1280.png',
                'product_name' => '復古冰箱',
                'description' => '淨水冰箱，讓您的家人時刻享受純淨健康的飲水。',
                'price' => '90000',
                'ori_price' => '120000',
                'category' => '冰箱',
                'selected' => NULL,
            ),
            20 =>
            array(
                'id' => 32,
                'pic_name' => '碗',
                'pic_dir' => './pictureTarget/Bowl.png',
                'product_name' => '碗',
                'description' => '舒適享用美食，一個優質碗讓用餐更加愉悅、更有品味。',
                'price' => '30',
                'ori_price' => '50',
                'category' => '碗',
                'selected' => NULL,
            ),
            21 =>
            array(
                'id' => 33,
                'pic_name' => '碗',
                'pic_dir' => './pictureTarget/Bowl2.webp',
                'product_name' => '精緻的碗',
                'description' => '精緻碗，展現您的獨特品味，讓每一餐都成為一場視覺盛宴。',
                'price' => '75',
                'ori_price' => '99',
                'category' => '碗',
                'selected' => NULL,
            ),
            22 =>
            array(
                'id' => 34,
                'pic_name' => '碗',
                'pic_dir' => './pictureTarget/Bowl3.jpg',
                'product_name' => '月光碗',
                'description' => '堅固耐用，選擇高品質碗，陪伴您和家人走過每一個美好時刻。',
                'price' => '65',
                'ori_price' => '85',
                'category' => '碗',
                'selected' => NULL,
            ),
            23 =>
            array(
                'id' => 35,
                'pic_name' => '碗',
                'pic_dir' => './pictureTarget/Bowl4.webp',
                'product_name' => '寶血之碗',
                'description' => '清新設計，讓您的餐桌增添色彩，為生活帶來更多驚喜和樂趣。',
                'price' => '40',
                'ori_price' => '60',
                'category' => '碗',
                'selected' => NULL,
            ),
            24 =>
            array(
                'id' => 36,
                'pic_name' => '碗',
                'pic_dir' => './pictureTarget/Bowl5.png',
                'product_name' => '橘子碗',
                'description' => '多功能碗，滿足您不同需求，從早餐到晚餐，一碗搞定。',
                'price' => '30',
                'ori_price' => '35',
                'category' => '碗',
                'selected' => NULL,
            ),
            25 =>
            array(
                'id' => 37,
                'pic_name' => '碗',
                'pic_dir' => './pictureTarget/Bowl6.webp',
                'product_name' => '彩虹小碗',
                'description' => '清新設計，讓您的餐桌增添色彩，為生活帶來更多驚喜和樂趣。',
                'price' => '65',
                'ori_price' => '75',
                'category' => '碗',
                'selected' => NULL,
            ),
            26 =>
            array(
                'id' => 38,
                'pic_name' => '碗',
                'pic_dir' => './pictureTarget/Bowl7.png',
                'product_name' => '木碗',
                'description' => '健康之選，選擇環保材料製成的碗，為您和家人的健康保駕護航，讓用餐更放心。',
                'price' => '70',
                'ori_price' => '90',
                'category' => '碗',
                'selected' => NULL,
            ),
            27 =>
            array(
                'id' => 39,
                'pic_name' => '夾子',
                'pic_dir' => './pictureTarget/clamp.jpg',
                'product_name' => '夾子',
                'description' => '夾子靈巧，為您的生活增添更多便利與靈活性，輕鬆處理大小事務。',
                'price' => '7',
                'ori_price' => '14',
                'category' => '夾子',
                'selected' => NULL,
            ),
            28 =>
            array(
                'id' => 40,
                'pic_name' => '夾子',
                'pic_dir' => './pictureTarget/clamp2.jpg',
                'product_name' => '夾子2',
                'description' => '堅固耐用，選擇高品質夾子，讓您放心使用，長久陪伴您的生活。',
                'price' => '3',
                'ori_price' => '6',
                'category' => '夾子',
                'selected' => NULL,
            ),
            29 =>
            array(
                'id' => 41,
                'pic_name' => '夾子',
                'pic_dir' => './pictureTarget/clamp3.webp',
                'product_name' => '夾子3',
                'description' => '多功能夾子，輕鬆解決各種困難，讓您的工作和生活更加順暢。',
                'price' => '19',
                'ori_price' => '23',
                'category' => '夾子',
                'selected' => NULL,
            ),
            30 =>
            array(
                'id' => 42,
                'pic_name' => '夾子',
                'pic_dir' => './pictureTarget/clamp4.jpg',
                'product_name' => '夾子4',
                'description' => '設計時尚，夾子不僅是工具，更是展現您個人品味的時尚配件。',
                'price' => '12',
                'ori_price' => '19',
                'category' => '夾子',
                'selected' => NULL,
            ),
            31 =>
            array(
                'id' => 43,
                'pic_name' => '夾子',
                'pic_dir' => './pictureTarget/clamp5.jpg',
                'product_name' => '夾子5',
                'description' => '創意應用，夾子讓您的創意無限發揮，為生活增添更多樂趣和驚喜。',
                'price' => '16',
                'ori_price' => '23',
                'category' => '夾子',
                'selected' => NULL,
            ),
            32 =>
            array(
                'id' => 44,
                'pic_name' => '夾子',
                'pic_dir' => './pictureTarget/clamp6.png',
                'product_name' => '夾子6',
                'description' => '夾子實用，簡單而有效的解決方案，讓您輕鬆應對各種日常挑戰。',
                'price' => '15',
                'ori_price' => '30',
                'category' => '夾子',
                'selected' => NULL,
            ),
            33 =>
            array(
                'id' => 45,
                'pic_name' => '夾子',
                'pic_dir' => './pictureTarget/clamp7.png',
                'product_name' => '夾子7',
                'description' => '環保夾子，選擇可回收材料製成的夾子，愛護地球，從小夾子做起，實踐綠色生活。',
                'price' => '30',
                'ori_price' => '45',
                'category' => '夾子',
                'selected' => NULL,
            ),
            34 =>
            array(
                'id' => 46,
                'pic_name' => '筆電',
                'pic_dir' => './pictureTarget/laptop1.webp',
                'product_name' => '筆電',
                'description' => '極致輕薄，讓您隨心所欲地帶著筆電，掌握整個世界。',
                'price' => '20000',
                'ori_price' => '30000',
                'category' => '筆電',
                'selected' => NULL,
            ),
            35 =>
            array(
                'id' => 47,
                'pic_name' => '筆電',
                'pic_dir' => './pictureTarget/laptop2.png',
                'product_name' => '筆電2',
                'description' => '強大效能，每一次操作都如行雲流水，讓您事半功倍，輕鬆完成任務。',
                'price' => '40000',
                'ori_price' => '45000',
                'category' => '筆電',
                'selected' => NULL,
            ),
            36 =>
            array(
                'id' => 48,
                'pic_name' => '筆電',
                'pic_dir' => './pictureTarget/laptop3.png',
                'product_name' => '筆電3',
                'description' => '靈活轉換，從辦公到娛樂，筆電滿足您多重需求，隨時隨地，無所不至。',
                'price' => '23000',
                'ori_price' => '25000',
                'category' => '筆電',
                'selected' => NULL,
            ),
            37 =>
            array(
                'id' => 49,
                'pic_name' => '筆電',
                'pic_dir' => './pictureTarget/laptop4.jpg',
                'product_name' => '紅色筆電',
                'description' => '清晰螢幕，沉浸式體驗，呈現最真實、最生動的影像，讓您身臨其境。',
                'price' => '35000',
                'ori_price' => '36000',
                'category' => '筆電',
                'selected' => NULL,
            ),
            38 =>
            array(
                'id' => 50,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/laptop5.png',
                'product_name' => '筆電4',
                'description' => '智能連接，筆電讓您與世界無縫接軌，隨時掌握最新資訊，保持前沿。',
                'price' => '28000',
                'ori_price' => '29000',
                'category' => '筆電',
                'selected' => NULL,
            ),
            39 =>
            array(
                'id' => 51,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/laptop6.png',
                'product_name' => '筆電5',
                'description' => '長續航力，無需擔心電力不足，讓您專注於創造，不受限制。',
                'price' => '38000',
                'ori_price' => '42000',
                'category' => '筆電',
                'selected' => NULL,
            ),
            40 =>
            array(
                'id' => 52,
                'pic_name' => '',
                'pic_dir' => './pictureTarget/laptop7.png',
                'product_name' => '藍色妖姬',
                'description' => '時尚設計，不僅是工具，更是生活方式的象徵，展現您的品味與風格。',
                'price' => '36000',
                'ori_price' => '39000',
                'category' => '筆電',
                'selected' => NULL,
            ),
            41 =>
            array(
                'id' => 53,
                'pic_name' => '鍋子',
                'pic_dir' => './pictureTarget/pan2.png',
                'product_name' => '鍋子',
                'description' => '傳熱均勻，讓您的料理更加美味，每一口都是家的味道。',
                'price' => '500',
                'ori_price' => '600',
                'category' => '鍋子',
                'selected' => NULL,
            ),
            42 =>
            array(
                'id' => 54,
                'pic_name' => '鍋子',
                'pic_dir' => './pictureTarget/pan3.png',
                'product_name' => '鍋子2',
                'description' => '耐用不鏽，堅固的鍋子，為您的廚房生活提供持久的伴侶，值得信賴。',
                'price' => '600',
                'ori_price' => '700',
                'category' => '鍋子',
                'selected' => NULL,
            ),
            43 =>
            array(
                'id' => 55,
                'pic_name' => '鍋子',
                'pic_dir' => './pictureTarget/pan4.png',
                'product_name' => '鍋子3',
                'description' => '多功能料理，一鍋多用，輕鬆應對各種烹飪需求，讓您成為廚藝大師。',
                'price' => '700',
                'ori_price' => '800',
                'category' => '鍋子',
                'selected' => NULL,
            ),
            44 =>
            array(
                'id' => 56,
                'pic_name' => '鍋子',
                'pic_dir' => './pictureTarget/pan5.png',
                'product_name' => '多鍋子',
                'description' => '精美外觀，不僅是廚房工具，更是家居裝飾，為您的廚房增添色彩和風采。',
                'price' => '700',
                'ori_price' => '800',
                'category' => '鍋子',
                'selected' => NULL,
            ),
            45 =>
            array(
                'id' => 57,
                'pic_name' => '鍋子',
                'pic_dir' => './pictureTarget/pan7.png',
                'product_name' => '鍋子4',
                'description' => '環保健康，選擇無毒材質製作的鍋子，保障您和家人的健康，享受美味生活。',
                'price' => '500',
                'ori_price' => '700',
                'category' => '鍋子',
                'selected' => NULL,
            ),
            46 =>
            array(
                'id' => 58,
                'pic_name' => '燈泡',
                'pic_dir' => './pictureTarget/lightbulb2.png',
                'product_name' => '燈泡',
                'description' => '照亮未來，一盞燈泡，點亮您的生活，為您帶來無限可能。',
                'price' => '30',
                'ori_price' => '45',
                'category' => '燈泡',
                'selected' => NULL,
            ),
            47 =>
            array(
                'id' => 59,
                'pic_name' => '燈泡',
                'pic_dir' => './pictureTarget/lightbulb3.jpg',
                'product_name' => '燈泡2',
                'description' => '節能環保，選擇高效能燈泡，照明之餘，還為地球盡一份心力。',
                'price' => '65',
                'ori_price' => '95',
                'category' => '燈泡',
                'selected' => NULL,
            ),
            48 =>
            array(
                'id' => 60,
                'pic_name' => '燈泡',
                'pic_dir' => './pictureTarget/lightbulb4.png',
                'product_name' => '燈泡3',
                'description' => '柔和照明，燈泡營造溫馨氛圍，讓家更加舒適，心靈更加溫暖。',
                'price' => '12',
                'ori_price' => '65',
                'category' => '燈泡',
                'selected' => NULL,
            ),
            49 =>
            array(
                'id' => 61,
                'pic_name' => '燈泡',
                'pic_dir' => './pictureTarget/lightbulb5.jpg',
                'product_name' => '燈泡4',
                'description' => '創意設計，不僅是照明工具，更是家居裝飾的亮點，展現個人風格。',
                'price' => '45',
                'ori_price' => '65',
                'category' => '燈泡',
                'selected' => NULL,
            ),
            50 =>
            array(
                'id' => 62,
                'pic_name' => '燈泡',
                'pic_dir' => './pictureTarget/lightbulb6.webp',
                'product_name' => '燈泡5',
                'description' => '智慧連接，智能燈泡，為您的生活增添更多便利和樂趣，隨心所欲掌控光明。',
                'price' => '60',
                'ori_price' => '80',
                'category' => '燈泡',
                'selected' => NULL,
            ),
            51 =>
            array(
                'id' => 63,
                'pic_name' => '燈泡',
                'pic_dir' => './pictureTarget/lightbulb7.png',
                'product_name' => '燈泡6',
                'description' => '持久耐用，高品質燈泡，長久陪伴您的生活旅程，照亮每一個重要時刻。',
                'price' => '120',
                'ori_price' => '150',
                'category' => '燈泡',
                'selected' => NULL,
            ),
            52 =>
            array(
                'id' => 64,
                'pic_name' => '墨鏡',
                'pic_dir' => './pictureTarget/sunglasses1.png',
                'product_name' => '墨鏡',
                'description' => '時尚魅力，一副墨鏡，展現您的個性風采，引領潮流風潮。',
                'price' => '300',
                'ori_price' => '350',
                'category' => '墨鏡',
                'selected' => NULL,
            ),
            53 =>
            array(
                'id' => 66,
                'pic_name' => '墨鏡',
                'pic_dir' => './pictureTarget/sunglasses3.jpg',
                'product_name' => '墨鏡2',
                'description' => '舒適配戴，輕盈材質，墨鏡質感舒適，讓您長時間戴著也不感壓力。',
                'price' => '400',
                'ori_price' => '450',
                'category' => '墨鏡',
                'selected' => NULL,
            ),
            54 =>
            array(
                'id' => 67,
                'pic_name' => '墨鏡',
                'pic_dir' => './pictureTarget/sunglasses4.png',
                'product_name' => '墨鏡3',
                'description' => '清晰視界，優質鏡片，墨鏡讓您看見更真實的世界，享受清晰視野。',
                'price' => '400',
                'ori_price' => '450',
                'category' => '墨鏡',
                'selected' => NULL,
            ),
            55 =>
            array(
                'id' => 68,
                'pic_name' => '墨鏡',
                'pic_dir' => './pictureTarget/sunglasses5.jpg',
                'product_name' => '墨鏡4',
                'description' => '多功能設計，從時尚到運動，墨鏡滿足您不同場合需求，為您帶來全方位保護。',
                'price' => '450',
                'ori_price' => '500',
                'category' => '墨鏡',
                'selected' => NULL,
            ),
            56 =>
            array(
                'id' => 69,
                'pic_name' => '墨鏡',
                'pic_dir' => './pictureTarget/sunglasses6.jpg',
                'product_name' => '墨鏡5',
                'description' => '霸氣外型，墨鏡是您展現自信與魅力的利器，征服世界從這裡開始。',
                'price' => '500',
                'ori_price' => '550',
                'category' => '墨鏡',
                'selected' => NULL,
            ),
            57 =>
            array(
                'id' => 70,
                'pic_name' => '墨鏡',
                'pic_dir' => './pictureTarget/sunglasses7.webp',
                'product_name' => '墨鏡6',
                'description' => '健康首選，選擇專業防紫外線墨鏡，愛護眼睛健康，享受無憂陽光生活。',
                'price' => '550',
                'ori_price' => '600',
                'category' => '墨鏡',
                'selected' => NULL,
            ),
            58 =>
            array(
                'id' => 71,
                'pic_name' => '沙發',
                'pic_dir' => './pictureTarget/sofa2.webp',
                'product_name' => '沙發',
                'description' => '舒適享受，一把沙發，承載著您的休憩與放鬆，讓每一刻都如家。',
                'price' => '40000',
                'ori_price' => '50000',
                'category' => '沙發',
                'selected' => NULL,
            ),
            59 =>
            array(
                'id' => 72,
                'pic_name' => '沙發',
                'pic_dir' => './pictureTarget/sofa3.jpg',
                'product_name' => '沙發2',
                'description' => '精緻工藝，沙發不僅是家具，更是藝術品，展現您的品味與格調。',
                'price' => '35000',
                'ori_price' => '45000',
                'category' => '沙發',
                'selected' => NULL,
            ),
            60 =>
            array(
                'id' => 73,
                'pic_name' => '沙發',
                'pic_dir' => './pictureTarget/sofa4.webp',
                'product_name' => '沙發3',
                'description' => '家的溫暖，沙發見證家人相聚的溫馨時刻，共度美好生活。',
                'price' => '50000',
                'ori_price' => '55000',
                'category' => '沙發',
                'selected' => NULL,
            ),
            61 =>
            array(
                'id' => 74,
                'pic_name' => '沙發',
                'pic_dir' => './pictureTarget/sofa5.png',
                'product_name' => '沙發4',
                'description' => '多功能設計，從休閒到娛樂，沙發滿足您多樣化的生活需求，舒適無比。',
                'price' => '55000',
                'ori_price' => '56000',
                'category' => '沙發',
                'selected' => NULL,
            ),
            62 =>
            array(
                'id' => 75,
                'pic_name' => '沙發',
                'pic_dir' => './pictureTarget/sofa6.jpg',
                'product_name' => '沙發5',
                'description' => '家的中心，沙發聚集家人情感，打造家的溫暖中心，緊緊相擁，永遠在一起。',
                'price' => '60000',
                'ori_price' => '65000',
                'category' => '沙發',
                'selected' => NULL,
            ),
            63 =>
            array(
                'id' => 76,
                'pic_name' => '桌子',
                'pic_dir' => './pictureTarget/table1.jpg',
                'product_name' => '桌子',
                'description' => '實用美觀，一張桌子，打造您的工作與生活中心，兼顧功能與美感。',
                'price' => '3000',
                'ori_price' => '3500',
                'category' => '桌子',
                'selected' => NULL,
            ),
            64 =>
            array(
                'id' => 77,
                'pic_name' => '桌子',
                'pic_dir' => './pictureTarget/table2.jpg',
                'product_name' => '桌子2',
                'description' => '堅固耐用，選擇高品質桌子，陪伴您度過無數美好時光，穩固支撐一切。',
                'price' => '3500',
                'ori_price' => '4000',
                'category' => '桌子',
                'selected' => NULL,
            ),
            65 =>
            array(
                'id' => 78,
                'pic_name' => '桌子',
                'pic_dir' => './pictureTarget/table3.png',
                'product_name' => '桌子3',
                'description' => '多功能設計，桌子滿足您各種需求，從工作到娛樂，一桌搞定所有事務。',
                'price' => '4000',
                'ori_price' => '4500',
                'category' => '桌子',
                'selected' => NULL,
            ),
            66 =>
            array(
                'id' => 79,
                'pic_name' => '桌子',
                'pic_dir' => './pictureTarget/table4.png',
                'product_name' => '桌子4',
                'description' => '設計簡約，風格獨特，桌子為您的家居增添與眾不同的個性魅力。',
                'price' => '4500',
                'ori_price' => '5000',
                'category' => '桌子',
                'selected' => NULL,
            ),
            67 =>
            array(
                'id' => 80,
                'pic_name' => '桌子',
                'pic_dir' => './pictureTarget/table5.png',
                'product_name' => '桌子5',
                'description' => '空間儲存，桌子設計巧妙，提供額外儲物空間，讓空間更加整潔有序。',
                'price' => '5000',
                'ori_price' => '5600',
                'category' => '桌子',
                'selected' => NULL,
            ),
            68 =>
            array(
                'id' => 81,
                'pic_name' => '桌子',
                'pic_dir' => './pictureTarget/table6.png',
                'product_name' => '桌子6',
                'description' => '品質保證，桌子精心製作，經久不衰，成為家中最值得信賴的家具之一。',
                'price' => '6000',
                'ori_price' => '7000',
                'category' => '桌子',
                'selected' => NULL,
            ),
            69 =>
            array(
                'id' => 82,
                'pic_name' => '桌子',
                'pic_dir' => './pictureTarget/table7.png',
                'product_name' => '桌子7',
                'description' => '家的聚焦點，桌子是家人共聚的場所，談笑風生，創造無數美好回憶。',
                'price' => '8000',
                'ori_price' => '9000',
                'category' => '桌子',
                'selected' => NULL,
            ),
            70 =>
            array(
                'id' => 83,
                'pic_name' => 'wifi',
                'pic_dir' => './pictureTarget/wifi1.png',
                'product_name' => 'wifi',
                'description' => '無限連接，一台WiFi機，讓您隨時隨地享受高速網路，連接世界每一個角落。',
                'price' => '3000',
                'ori_price' => '4500',
                'category' => 'wifi',
                'selected' => NULL,
            ),
            71 =>
            array(
                'id' => 84,
                'pic_name' => 'wifi',
                'pic_dir' => './pictureTarget/wifi1.png',
                'product_name' => 'wifi2',
                'description' => '穩定速度，WiFi機提供快速穩定的網路連接，讓您暢享流暢網路體驗。',
                'price' => '3500',
                'ori_price' => '4000',
                'category' => 'wifi',
                'selected' => NULL,
            ),
            72 =>
            array(
                'id' => 85,
                'pic_name' => 'wifi',
                'pic_dir' => './pictureTarget/wifi3.png',
                'product_name' => 'wifi3',
                'description' => '智能覆蓋，WiFi機智能覆蓋您的整個家庭，無死角，讓網路無處不在。',
                'price' => '4000',
                'ori_price' => '4500',
                'category' => 'wifi',
                'selected' => NULL,
            ),
            73 =>
            array(
                'id' => 86,
                'pic_name' => 'wifi',
                'pic_dir' => './pictureTarget/wifi4.jpg',
                'product_name' => 'wifi4',
                'description' => '簡單設置，一鍵連接，WiFi機輕鬆設置，即刻享受無縫網路體驗。',
                'price' => '4500',
                'ori_price' => '5500',
                'category' => 'wifi',
                'selected' => NULL,
            ),
            74 =>
            array(
                'id' => 87,
                'pic_name' => 'wifi',
                'pic_dir' => './pictureTarget/wifi5.png',
                'product_name' => 'wifi5',
                'description' => '安全保障，WiFi機提供強大的安全功能，保護您的網路免受外界威脅。',
                'price' => '5000',
                'ori_price' => '5500',
                'category' => 'wifi',
                'selected' => NULL,
            ),
            75 =>
            array(
                'id' => 88,
                'pic_name' => 'wifi',
                'pic_dir' => './pictureTarget/wifi6.png',
                'product_name' => 'wifi6',
                'description' => '無線生活，WiFi機讓您擺脫繁瑣的有線連接，自由自在享受無線生活。',
                'price' => '5600',
                'ori_price' => '6500',
                'category' => 'wifi',
                'selected' => NULL,
            ),
            76 =>
            array(
                'id' => 89,
                'pic_name' => '洗衣機',
                'pic_dir' => './pictureTarget/washing-machine2.png',
                'product_name' => '洗衣機',
                'description' => '輕鬆洗淨，一台洗衣機，讓您輕鬆處理家中大小衣物，省時又省力。',
                'price' => '8000',
                'ori_price' => '9000',
                'category' => '洗衣機',
                'selected' => NULL,
            ),
            77 =>
            array(
                'id' => 90,
                'pic_name' => '洗衣機',
                'pic_dir' => './pictureTarget/washing-machine3.png',
                'product_name' => '洗衣機2',
                'description' => '智慧清洗，洗衣機提供智能程序，適應各種衣物材質，保證清潔效果。',
                'price' => '9000',
                'ori_price' => '10000',
                'category' => '洗衣機',
                'selected' => NULL,
            ),
            78 =>
            array(
                'id' => 91,
                'pic_name' => '洗衣機',
                'pic_dir' => './pictureTarget/washing-machine4.png',
                'product_name' => '洗衣機3',
                'description' => '節能環保，洗衣機採用高效節能技術，為您的家庭生活省下更多能源。',
                'price' => '9500',
                'ori_price' => '15000',
                'category' => '洗衣機',
                'selected' => NULL,
            ),
            79 =>
            array(
                'id' => 92,
                'pic_name' => '洗衣機',
                'pic_dir' => './pictureTarget/washing-machine5.png',
                'product_name' => '洗衣機4',
                'description' => '溫和呵護，洗衣機設有柔和洗衣模式，呵護衣物纖維，延長衣物壽命。',
                'price' => '11000',
                'ori_price' => '15000',
                'category' => '洗衣機',
                'selected' => NULL,
            ),
            80 =>
            array(
                'id' => 93,
                'pic_name' => '洗衣機',
                'pic_dir' => './pictureTarget/washing-machine6.png',
                'product_name' => '洗衣機5',
                'description' => '多功能選擇，洗衣機提供多種洗衣模式，滿足您不同衣物清洗需求。',
                'price' => '12000',
                'ori_price' => '16000',
                'category' => '洗衣機',
                'selected' => NULL,
            ),
            81 =>
            array(
                'id' => 94,
                'pic_name' => '洗衣機',
                'pic_dir' => './pictureTarget/washing-machine7.png',
                'product_name' => '洗衣機6',
                'description' => '時尚外觀，洗衣機設計時尚美觀，成為家中的亮點，提升家居品味。',
                'price' => '6500',
                'ori_price' => '7500',
                'category' => '洗衣機',
                'selected' => NULL,
            ),
            82 =>
            array(
                'id' => 95,
                'pic_name' => '吸塵器',
                'pic_dir' => './pictureTarget/vaccum.jpg',
                'product_name' => '吸塵器1',
                'description' => '一吸即凈，吸塵器讓清潔變得輕鬆，輕輕一吸，家居焕然一新。',
                'price' => '1000',
                'ori_price' => '2000',
                'category' => '吸塵器',
                'selected' => NULL,
            ),
            83 =>
            array(
                'id' => 96,
                'pic_name' => '吸塵器',
                'pic_dir' => './pictureTarget/vacuum2.png',
                'product_name' => '吸塵器2',
                'description' => '強大吸力，吸塵器輕鬆處理各種灰塵、毛髮，為您打造清潔無死角的家居環境。',
                'price' => '1500',
                'ori_price' => '2500',
                'category' => '吸塵器',
                'selected' => NULL,
            ),
            84 =>
            array(
                'id' => 97,
                'pic_name' => '吸塵器',
                'pic_dir' => './pictureTarget/vacuum3.jpg',
                'product_name' => '吸塵器3',
                'description' => '靜音設計，吸塵器提供靜音操作，讓您在清潔時享受寧靜舒適的環境。',
                'price' => '2000',
                'ori_price' => '3000',
                'category' => '吸塵器',
                'selected' => NULL,
            ),
            85 =>
            array(
                'id' => 98,
                'pic_name' => '吸塵器',
                'pic_dir' => './pictureTarget/vacuum4.png',
                'product_name' => '吸塵器4',
                'description' => '多功能配件，吸塵器附帶多款配件，滿足各種清潔需求，一機多用，方便實用。',
                'price' => '3500',
                'ori_price' => '4500',
                'category' => '吸塵器',
                'selected' => NULL,
            ),
            86 =>
            array(
                'id' => 99,
                'pic_name' => '吸塵器',
                'pic_dir' => './pictureTarget/vacuum5.png',
                'product_name' => '吸塵器5',
                'description' => '高效濾網，吸塵器搭載高效濾網，過濾微小塵埃，讓家居空氣更清新。',
                'price' => '4500',
                'ori_price' => '5500',
                'category' => '吸塵器',
                'selected' => NULL,
            ),
            87 =>
            array(
                'id' => 100,
                'pic_name' => '吸塵器',
                'pic_dir' => './pictureTarget/vacuum6.png',
                'product_name' => '吸塵器6',
                'description' => '輕巧便攜，吸塵器設計輕巧便攜，清潔無所不在，讓您隨時保持家居清潔。',
                'price' => '6000',
                'ori_price' => '6500',
                'category' => '吸塵器',
                'selected' => NULL,
            ),
            88 =>
            array(
                'id' => 101,
                'pic_name' => '吸塵器',
                'pic_dir' => './pictureTarget/vacuum7.png',
                'product_name' => '吸塵器7',
                'description' => '健康居家，吸塵器是家居清潔的必備利器，為您和家人打造舒適健康的生活環境。',
                'price' => '7000',
                'ori_price' => '7500',
                'category' => '吸塵器',
                'selected' => NULL,
            ),
        ));
    }
}